---
# Create Vaultwarden Directory
- name: Create Vaultwarden Directory
  ansible.builtin.file:
    path: ${{ infra_vaultwarden_dir }}
    state:
    owner:
    group:
    mode:

# Template Vaultwarden Env
- name: Template the Vaultwarden Env
  ansible.builtin.template:
    src:
    dest:
    owner:
    group:
    mode:

# Template Vaultwarden Container
- name: Template the Vaultwarden Container
  ansible.builtin.template:
    src:
    dest:
    owner:
    group:
    mode:

# Start Vaultwarden Service
- name: Start the Vaultwarden Stack
  community.docker.docker_compose_v2:
    project_src:
    state: present
    pull: always
