---
# install watchdog
- name: Install Watchdog
  ansible.builtin.apt:
    name: watchdog
    state: present

# Configure Watchdog
- name: Configure Watchdog
  ansible.builtin.template:
    src:
    dest:
    owner:
    group:
    mode:
  become: true

# Start the Watchdog Service
- name: Start watchdog Service
  ansible.builtin.service:
    name: watchdog
    enabled: true
    state: present
  become: true
