---
- name: Get existing stages
  ansible.builtin.uri:
    url: "{{ authentik_api_url }}/api/v3/stages/all/?page_size=10000"
    method: GET
    headers:
      Authorization: "Bearer {{ authentik_token }}"
    validate_certs: "{{ authentik_api_validate_certs }}"
    status_code: [200]
    timeout: "{{ authentik_api_call_timeout }}"
  register: authentik_existing_stages
  retries: "{{ authentik_api_call_retries }}"
  delay: "{{ authentik_api_call_delay }}"

- name: Get existing redirect stages
  ansible.builtin.uri:
    url: "{{ authentik_api_url }}/api/v3/stages/redirect/?page_size=10000"
    method: GET
    headers:
      Authorization: "Bearer {{ authentik_token }}"
    validate_certs: "{{ authentik_api_validate_certs }}"
    status_code: [200]
    timeout: "{{ authentik_api_call_timeout }}"
  register: authentik_existing_redirect_stages
  retries: "{{ authentik_api_call_retries }}"
  delay: "{{ authentik_api_call_delay }}"

- name: Get existing flows
  ansible.builtin.uri:
    url: "{{ authentik_api_url }}/api/v3/flows/instances/?page_size=10000"
    method: GET
    headers:
      Authorization: "Bearer {{ authentik_token }}"
    validate_certs: "{{ authentik_api_validate_certs }}"
    status_code: [200]
    timeout: "{{ authentik_api_call_timeout }}"
  register: authentik_existing_flows
  retries: "{{ authentik_api_call_retries }}"
  delay: "{{ authentik_api_call_delay }}"

- name: Assert that target flow exist
  when:
    - stage.target_flow_slug is defined
    - stage.target_flow_slug | length > 0
  ansible.builtin.assert:
    that: >-
      stage.target_flow_slug in authentik_existing_flows.json.results | map(attribute='slug') | list or
      stage.target_flow_slug in _authentik_config.flows.list | map(attribute='slug') | list
    fail_msg: "Flow '{{ stage.target_flow_slug }}' not found in existing flows nor planned flows"
    quiet: true

- name: "{{ ('Create' if new_stage else 'Update') ~ ' stage: ' ~ stage.name }}"
  ansible.builtin.uri:
    url: "{{ authentik_api_url }}/api/v3/stages/redirect/{{ stage_pk ~ '/' if not new_stage}}"
    method: "{{ 'POST' if new_stage else 'PATCH' }}"
    headers:
      Authorization: "Bearer {{ authentik_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      name: "{{ stage.name }}"
      mode: "{{ stage.mode if 'mode' in stage or new_stage else omit }}"
      target_flow: "{{ target_flow_pk if 'target_flow_slug' in stage else omit }}"
      target_static: "{{ stage.target_static if 'target_static' in stage else omit }}"
      keep_context: "{{ stage.keep_context if 'keep_context' in stage else omit }}"
    validate_certs: "{{ authentik_api_validate_certs }}"
    status_code: ["{{ 201 if new_stage else 200 }}"]
    timeout: "{{ authentik_api_call_timeout }}"
  register: authentik_custom_stage
  vars:
    stage_pk: >-
      {{
        authentik_existing_stages.json.results
        | selectattr('name', 'equalto', stage.name)
        | map(attribute='pk')
        | first
        | default(none)
      }}
    new_stage: "{{ stage_pk is none }}"
    target_flow_pk: >-
      {{
        authentik_existing_flows.json.results
        | selectattr('slug', 'equalto', stage.target_flow_slug)
        | map(attribute='pk')
        | first
        | default(none)
      }}
  changed_when: >-
    new_stage or
    (authentik_custom_stage.json
    !=
    (authentik_existing_redirect_stages.json.results
    | selectattr('pk', 'equalto', stage_pk)
    | first
    | default({})))
  retries: "{{ authentik_api_call_retries }}"
  delay: "{{ authentik_api_call_delay }}"
