---
- name: Get existing policies
  ansible.builtin.uri:
    url: "{{ authentik_api_url }}/api/v3/policies/all/?page_size=10000"
    method: GET
    headers:
      Authorization: "Bearer {{ authentik_token }}"
    validate_certs: "{{ authentik_api_validate_certs }}"
    status_code: [200]
    timeout: "{{ authentik_api_call_timeout }}"
  register: authentik_existing_policies
  retries: "{{ authentik_api_call_retries }}"
  delay: "{{ authentik_api_call_delay }}"

- name: Get existing password policies
  ansible.builtin.uri:
    url: "{{ authentik_api_url }}/api/v3/policies/password/?page_size=10000"
    method: GET
    headers:
      Authorization: "Bearer {{ authentik_token }}"
    validate_certs: "{{ authentik_api_validate_certs }}"
    status_code: [200]
    timeout: "{{ authentik_api_call_timeout }}"
  register: authentik_existing_password_policies
  retries: "{{ authentik_api_call_retries }}"
  delay: "{{ authentik_api_call_delay }}"

- name: "{{ ('Create' if new_policy else 'Update') ~ ' policy: ' ~ policy.name }}"
  ansible.builtin.uri:
    url: "{{ authentik_api_url }}/api/v3/policies/password/{{ policy_pk ~ '/' if not new_policy}}"
    method: "{{ 'POST' if new_policy else 'PATCH' }}"
    headers:
      Authorization: "Bearer {{ authentik_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      name: "{{ policy.name }}"
      execution_logging: "{{ policy.execution_logging if 'execution_logging' in policy else omit }}"
      password_field: "{{ policy.password_field if 'password_field' in policy else omit }}"
      amount_digits: "{{ policy.amount_digits if 'password_fiamount_digitseld' in policy else omit }}"
      amount_uppercase: "{{ policy.amount_uppercase if 'amount_uppercase' in policy else omit }}"
      amount_lowercase: "{{ policy.amount_lowercase if 'amount_lowercase' in policy else omit }}"
      amount_symbols: "{{ policy.amount_symbols if 'amount_symbols' in policy else omit }}"
      length_min: "{{ policy.length_min if 'length_min' in policy else omit }}"
      symbol_charset: "{{ policy.symbol_charset if 'symbol_charset' in policy else omit }}"
      error_message: "{{ policy.error_message if 'error_message' in policy else omit }}"
      check_static_rules: "{{ policy.check_static_rules if 'check_static_rules' in policy else omit }}"
      check_have_i_been_pwned: "{{ policy.check_have_i_been_pwned if 'check_have_i_been_pwned' in policy else omit }}"
      check_zxcvbn: "{{ policy.check_zxcvbn if 'check_zxcvbn' in policy else omit }}"
      hibp_allowed_count: "{{ policy.hibp_allowed_count if 'hibp_allowed_count' in policy else omit }}"
      zxcvbn_score_threshold: "{{ policy.zxcvbn_score_threshold if 'zxcvbn_score_threshold' in policy else omit }}"
    validate_certs: "{{ authentik_api_validate_certs }}"
    status_code: ["{{ 201 if new_policy else 200 }}"]
    timeout: "{{ authentik_api_call_timeout }}"
  register: authentik_custom_policy
  vars:
    policy_pk: >-
      {{
        authentik_existing_policies.json.results
        | selectattr('name', 'equalto', policy.name)
        | map(attribute='pk')
        | first
        | default(none)
      }}
    new_policy: "{{ policy_pk is none }}"
  changed_when: >-
    new_policy or
    (authentik_custom_policy.json
    !=
    (authentik_existing_password_policies.json.results
    | selectattr('pk', 'equalto', policy_pk)
    | first
    | default({})))
  retries: "{{ authentik_api_call_retries }}"
  delay: "{{ authentik_api_call_delay }}"
