---
- name: Check if Authentik is licenced
  ansible.builtin.uri:
    url: "{{ authentik_api_url }}/api/v3/enterprise/license/summary/"
    method: GET
    headers:
      Authorization: "Bearer {{ authentik_token }}"
    validate_certs: "{{ authentik_api_validate_certs }}"
    status_code: [200]
    timeout: "{{ authentik_api_call_timeout }}"
  register: authentik_licence_summary
  retries: "{{ authentik_api_call_retries }}"
  delay: "{{ authentik_api_call_delay }}"

- name: Show message when Authentik is not licenced
  when: authentik_licence_summary.json.status != 'valid'
  ansible.builtin.debug:
    msg: |-
      Authentik is not licenced !
      The policy {{ policy.name }} will be skipped
    verbosity: 1

- name: Create or update policy if Authentik is licenced
  when: authentik_licence_summary.json.status == 'valid' or authentik_licence_summary.json.status == 'expiry_soon'
  block:
    - name: Get existing policies
      ansible.builtin.uri:
        url: "{{ authentik_api_url }}/api/v3/policies/all/?page_size=10000"
        method: GET
        headers:
          Authorization: "Bearer {{ authentik_token }}"
        validate_certs: "{{ authentik_api_validate_certs }}"
        status_code: [200]
        timeout: "{{ authentik_api_call_timeout }}"
      register: authentik_existing_policies
      retries: "{{ authentik_api_call_retries }}"
      delay: "{{ authentik_api_call_delay }}"

    - name: Get existing unique_password policies
      ansible.builtin.uri:
        url: "{{ authentik_api_url }}/api/v3/policies/unique_password/?page_size=10000"
        method: GET
        headers:
          Authorization: "Bearer {{ authentik_token }}"
        validate_certs: "{{ authentik_api_validate_certs }}"
        status_code: [200]
        timeout: "{{ authentik_api_call_timeout }}"
      register: authentik_existing_unique_password_policies
      retries: "{{ authentik_api_call_retries }}"
      delay: "{{ authentik_api_call_delay }}"

    - name: "{{ ('Create' if new_policy else 'Update') ~ ' policy: ' ~ policy.name }}"
      ansible.builtin.uri:
        url: "{{ authentik_api_url }}/api/v3/policies/unique_password/{{ policy_pk ~ '/' if not new_policy}}"
        method: "{{ 'POST' if new_policy else 'PATCH' }}"
        headers:
          Authorization: "Bearer {{ authentik_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          name: "{{ policy.name }}"
          execution_logging: "{{ policy.execution_logging if 'execution_logging' in policy else omit }}"
          password_field: "{{ policy.password_field if 'password_field' in policy else omit }}"
          num_historical_passwords: "{{ policy.num_historical_passwords if 'num_historical_passwords' in policy else omit }}"
        validate_certs: "{{ authentik_api_validate_certs }}"
        status_code: ["{{ 201 if new_policy else 200 }}"]
        timeout: "{{ authentik_api_call_timeout }}"
      register: authentik_custom_policy
      vars:
        policy_pk: >-
          {{
            authentik_existing_policies.json.results
            | selectattr('name', 'equalto', policy.name)
            | map(attribute='pk')
            | first
            | default(none)
          }}
        new_policy: "{{ policy_pk is none }}"
      changed_when: >-
        new_policy or
        (authentik_custom_policy.json
        !=
        (authentik_existing_unique_password_policies.json.results
        | selectattr('pk', 'equalto', policy_pk)
        | first
        | default({})))
      retries: "{{ authentik_api_call_retries }}"
      delay: "{{ authentik_api_call_delay }}"
