# set Adguard Working Directory
- name: Create Adgaurd Working Directory
  ansible.builtin.file:
    path: "{{ INFRA_ADGUARD_WORKING_DIR }}"
    state: directory
    owner: root
    group: root
    mode:
  become: true

# Template Adgaurd env
- name: Template Adguard from .ENV
  ansible.builtin.template:
    src:
    dest:
    owner: root
    group: root
    mode:
  become: true

# Template Adgaurd Container
- name: Template the Adguard Container
  ansible.builtin.template:
    src:
    dest:
    owner: root
    group: root
    mode:
  become: true

# Start the Adgaurd Container
- name: Start the Adguard Container
  community.docker.docker_compose_v2:
    project_src:
    state: present
    pull: always
  become: true
