# set Adguard Working Directory
- name: Create Adgaurd Working Directory
  ansible.builtin.file:
  path: ${{ INFRA_ADGUARD_WORKING_DIR }}
  state: directory

# Template Adgaurd env
- name: Template Adguard from .ENV
  ansible.builtin.template:
    src:
    dest:
    owner:
    group:
    mode:

# Template Adgaurd Container
- name: Template the Adguard Container
  ansible.builtin.template:
    src:
    dest:
    owner:
    group:
    mode:

# Start the Adgaurd Container
- name: Start the Adguard Container
  community.docker.docker_compose_v2:
    project_src:
    state: present
    pull: always
