---

- name: Install Tailscale
  ansible.builtin.apt:
    name: tailscale
    state: present
  become: true

- name: Configure TailScale
  ansible.builtin.template:
    src:
    dest:
    owner: root
    group: root
    mode:
  become: true

- name: Start Tailscale
  ansible.builtin.service:
    name: tailscale
    enabled: true
    state: present
  become: true
