---

- name: Install Tailscale
  ansible.builtin.apt:
    name: tailscale
    state: present

- name: Configure TailScale
  ansible.builtin.template:
    src:
    dest:
    owner:
    group:
    mode:

- name: Start Tailscale
  ansible.builtin.service:
    name: tailscale
    enabled: true
    state: started
