# Traefik Container Service

# Set Traefik working directory
- name: Set Traefik Working Directory
  ansible.builtin.file:
    path: ${{ infra_traefik_dir }}
    state: directory

# Template Traefik Env
- name: Template the Traefik env
  ansible.builtin.template:
    src:
    dest:
    owner:
    group:
    mode:

# Template Traefik Container
- name: Template the Traefik Container
  ansible.builtin.template:
    src:
    dest:
    owner:
    group:
    mode:

# Start the Traefik Container
- name: Start the Traefik Container
  community.docker.docker_compose_v2:
    project_src:
    state: present
    pull: always
